In [39]:
import numpy as np
arr=np.array([5,10,15,20,25])

In [40]:
arr

array([ 5, 10, 15, 20, 25])

In [32]:
arr.ndim

2

In [45]:
arr[1:4:2]

array([10, 20])

In [53]:
na=np.array([[1,2,3],[4,5,6],[7,8,9,]])
na

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
na[2][2]

9

In [57]:
na[1,2]

6

In [68]:

na[:2,1:]

array([[2, 3],
       [5, 6]])

In [70]:
new=np.random.seed(123)

In [83]:
new=np.random.randint(1,101,25).reshape(5,5)
new


array([[89, 88, 70, 98, 51],
       [ 3, 19, 47, 46, 58],
       [36, 19, 92, 47, 55],
       [74, 82, 63, 68, 12],
       [27, 93, 76, 11,  4]])

In [88]:
new[1:2,1:4]

array([[19, 47, 46]])

In [90]:
new[3:,1:4]

array([[82, 63, 68],
       [93, 76, 11]])

In [100]:
ar=np.array([1,2,3,4,5])
var=ar.view()
var


array([1, 2, 3, 4, 5])

In [101]:
var[0]=22
var

array([22,  2,  3,  4,  5])

In [102]:
ar

array([22,  2,  3,  4,  5])

In [103]:
ass=np.arange(1,100)
ass

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [105]:
ass[ass%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [110]:
ass.reshape(-1,33)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99]])

In [112]:
m2=np.arange(1,20)
m2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [115]:
for i in m2:
    if i%2==0:
        print('even',i)
    else:
        print('odd',i)

odd 1
even 2
odd 3
even 4
odd 5
even 6
odd 7
even 8
odd 9
even 10
odd 11
even 12
odd 13
even 14
odd 15
even 16
odd 17
even 18
odd 19


In [116]:
np.random.seed(123)

In [117]:
m=np.random.randint(1,11,9).reshape(3,3)

In [118]:
m

array([[ 3,  3,  7],
       [ 2,  4, 10],
       [ 7,  2,  1]])

In [122]:
m.sum()

39

In [123]:
m.min()

1

In [124]:
m.max()

10

In [125]:
m,axis=1

TypeError: cannot unpack non-iterable int object

In [126]:
np.max(m,axis=0)

array([ 7,  4, 10])

In [127]:
import numpy as np

In [128]:
arr=np.array([1,2,3])

In [129]:
arr

array([1, 2, 3])

In [132]:
arra=np.arange(1,21)
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [134]:
np.five(20)

AttributeError: module 'numpy' has no attribute 'five'

In [135]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [139]:
da=np.arange(1,10).reshape(-1,3)

In [140]:
da


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:

rn=np.random.rand(1,25).reshape(2,-1)

ValueError: cannot reshape array of size 25 into shape (2,newaxis)

In [163]:
rn


array([[0.85497282, 0.7113918 , 0.39294441, 0.23130148, 0.38017471,
        0.5491621 , 0.55671906, 0.00413464, 0.63802252, 0.05764801,
        0.04302691, 0.87505113, 0.2925876 , 0.76276766, 0.36786526,
        0.87350227, 0.02942373, 0.55204372, 0.2402475 , 0.88480501,
        0.46023842, 0.19317033, 0.2936925 , 0.81792751, 0.55948738],
       [0.67792545, 0.80912668, 0.86857215, 0.41799246, 0.05893816,
        0.478459  , 0.52115943, 0.58063202, 0.309199  , 0.91988263,
        0.6553475 , 0.34924138, 0.54109404, 0.4490534 , 0.28232096,
        0.29587653, 0.56348098, 0.71519128, 0.51761868, 0.35204183,
        0.63277886, 0.87311902, 0.16788844, 0.98747832, 0.34941493],
       [0.82620513, 0.06546154, 0.00535329, 0.88694465, 0.91131813,
        0.19940777, 0.02755138, 0.81733492, 0.24182762, 0.05608301,
        0.06756083, 0.47387186, 0.50942926, 0.41679514, 0.25584293,
        0.38151211, 0.80738444, 0.81103914, 0.68618686, 0.99261363,
        0.40518518, 0.19017372, 0.48817449, 0.

In [168]:
import numpy as np

# Create a 2D array with dimensions (5, 5) and random numbers between 0 and 1
random_array_2d = np.random.rand(5, 5)

print(random_array_2d)


[[9.67511330e-01 2.81417524e-01 2.46395046e-01 7.75183545e-02
  8.92075490e-01]
 [3.45450188e-02 4.91475169e-01 9.04559704e-04 8.89198605e-01
  3.39397471e-01]
 [6.30818196e-01 3.30706548e-01 8.88989739e-01 7.29322390e-01
  9.43207745e-02]
 [7.06701207e-01 8.80416664e-01 5.40537818e-01 9.75730844e-01
  4.70003232e-01]
 [3.92036340e-02 5.13489350e-01 5.21840793e-01 5.79497239e-01
  8.37250764e-01]]


In [203]:
r2=np.arange(1,21).reshape(5,-1)
r2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [204]:
r2[r2%2==0]=-1

In [207]:
r2

array([[ 1, -1,  3, -1],
       [ 5, -1,  7, -1],
       [ 9, -1, 11, -1],
       [13, -1, 15, -1],
       [17, -1, 19, -1]])

In [209]:
r2
r2[3:4,1:3]

array([[-1, 15]])

In [192]:
a1=np.arange(1,7).reshape(2,-1)

In [193]:
a2=np.arange(6,12).reshape(2,-1)

In [194]:
a2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [195]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:

np.hstack((a1,a2))

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [197]:

np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [198]:
np.concatenate((a1,a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [214]:
a7=np.arange(1,10).reshape(3,3)

In [215]:
a7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])